### ISSUE TITLE
Evaluate integration of slideshow based on remark

### ISSUE THREAD

**Issue by prasanth-reddy-wavemaker-com** [wavemaker/docs#133]
https://remarkjs.com/#1 allows creation of slideshow based on markdown files.

In some cases instead of horizontal scroll of a big page, it may be more usable to visualise the page as a slideshow.

![image](https://user-images.githubusercontent.com/57487155/71817144-f4ed7e00-30aa-11ea-9f28-710dca608517.png)

**Comment by rnaresh** [comment]
https://docusaurus.io/blog/2018/09/11/Towards-Docusaurus-2#markdown

**...For Docusaurus 2, users can eject and choose their own markdown parser....**

**Comment by rnaresh** [comment]
closing this issue as we are able integrate remarkjs slideshow into the repo
