### ISSUE TITLE
Amazon deploy

### ISSUE THREAD

**Issue by midrissi** [wavemaker/docs#357]
I am not sure if this is the right place to write this issue, but I haven't found elsewhere.

My issue is related to Amazon deployment. Every time I try to configure an amazon deployment, I get this message:

![image](https://user-images.githubusercontent.com/3237344/98082849-b4e95a00-1e79-11eb-9cba-3cd5b2174c9c.png)

I have double checked the credentials, they are correct.

Please advice!

**Comment by neha2024** [comment]
Hi midrissi,
Can you please send an email to support@wavemaker.com for any issues so that we can involve the right team and help you solve the issue. 

Regards,
Neha

**Comment by rnaresh** [comment]
@midrissi This is meant for wavemaker docs related issues. Please contact support@wavemaker.com to help you solve the issue.
