### ISSUE TITLE
Issue with manual build wavemaker cordova project

### ISSUE THREAD

**Issue by mavericksthinker** [wavemaker/docs#410]
Hello, I am currently utilizing wavemaker to build a mobile app. After working on UI via the wavemaker platform I tried to export a Cordova zip file as mentioned in the document for the manual build. I have some questions regarding that :

1. Any changes made in the application, apart from index.html, app.js, app.css, are not reflected in the output ( i.e changes made in the Pages directory ). Is there a way to enable that? as implementing code on the wavemaker platform and exporting it out to local for checking the native functionality is cumbersome and requires a lot of time to do perform changes in the application.
 
2. I am trying to integrate `cordova-plugin-customurlscheme` into the application ( which can't be installed via wm CLI, so have to be done via wavemaker platform. Is there any alternative for this as well? ). I am able to trigger deep-linking but I am unable to trigger 
`function handleOpenURL(url) {
      console.log("received url: " + url);
    }  `
    
in app.js.

I can trigger this via script tag in index.html but as App is undefined so I am not able to navigate to the required login page. 

Is there a way to receive the handleOpenURL in app.js so that I can utilize the params for login purposes or trigger navigation with page param from index.html?

Any help will be appreciated.

**Comment by prasanth-reddy-wavemaker-com** [comment]
Hello, 

Thanks for using WaveMaker. However, this repository is for reporting issues against our documentation. I have forwarded your question to our product support and they will try reaching you on the email you have used to signup for WaveMaker account.
