### ISSUE TITLE
Documentation links are not accessible

### ISSUE THREAD

**Issue by prasanth-reddy-wavemaker-com** [wavemaker/docs#52]
Many of the documentation links are not accessible. We are seeing Access denied message for some and few are pointing to the home page of the docs.  
Also, there are alignment issues with the images. 
Below are a few links that we noted. 

1. https://www.wavemaker.com/learn/how-tos/how-tos-live-form/
2. https://www.wavemaker.com/learn/how-tos/using-live-form/
3. https://www.wavemaker.com/learn/app-development/widgets/chart/onbeforerender/
4. https://www.wavemaker.com/learn/app-development/widgets/form-widgets/rating-widget/   

- [ ] Check WordPress dump to see how these didn't get migrated.
- [ ] Setup alert on 404s happening on cloudfront that is powering the learn site
- [ ] Proper error page instead of XML response from AWS S3

**Comment by prasanth-reddy-wavemaker-com** [comment]
https://github.com/aws-amplify/amplify-console/issues/70
Amplify console has this feature
https://stackoverflow.com/questions/56634467/problems-setting-up-404-page-on-gatsby-site-in-aws-amplify

**Comment by prasanth-reddy-wavemaker-com** [comment]
Amplify has a bug that is preventing custom configured error pages from being served.

**Comment by swethakundaram-wm** [comment]
These are fixed in #74

**Comment by prasanth-reddy-wavemaker-com** [comment]
Reopening this since we still are not getting 404 reported on GA site.

**Comment by prasanth-reddy-wavemaker-com** [comment]
Trying to detect these by crawling the site via cypress.

**Comment by prasanth-reddy-wavemaker-com** [comment]
@saibonala has written a program that detects errors in pages by scanning img, anchor tags. This is in https://github.com/wavemaker/docs/tree/report-broken-links branch

**Comment by prasanth-reddy-wavemaker-com** [comment]
[broken-urls.txt](https://github.com/wavemaker/docs/files/3982960/broken-urls.txt)

**Comment by swethakundaram** [comment]
Is there a way to set up a redirection?
