### ISSUE TITLE
Code snippets are shown with additional slash(\) symbol in below link of doc

### ISSUE THREAD

**Issue by BhavaniGaneshBalagam** [wavemaker/docs#66]
[](https://www.wavemaker.com/learn/app-development/variables/navigation-action/)

**Comment by BhavaniGaneshBalagam** [comment]
Following  documentation link shows code snippets with an additional slash (\) symbol which causing code is not working. Need to remove the slash from codes in-page link.
https://www.wavemaker.com/learn/app-development/variables/navigation-action/

**Comment by prasanth-reddy-wavemaker-com** [comment]
@swethakundaram good job on fixing this so quickly.
@BhavaniGaneshBalagam Its deployed now, can you verify and close this?

**Comment by BhavaniGaneshBalagam** [comment]
Observed issue in below doc links:

https://www.wavemaker.com/learn/how-tos/sending-email-using-java-service
https://www.wavemaker.com/learn/how-tos/using-filter-conditions-variable
https://www.wavemaker.com/learn/how-tos/implementing-forgot-password-feature-using-java-service
https://www.wavemaker.com/learn/how-tos/accessing-rest-apis-java-service

**Comment by swethakundaram-wm** [comment]
Thanks. There is huge list of docs with similar problem. I have noted them. I am working on it.

**Comment by prasanth-reddy-wavemaker-com** [comment]
This is fixed right? Can we close it? @BhavaniGaneshBalagam @swethakundaram

**Comment by swethakundaram-wm** [comment]
Not yet. Still, there are many documents that contain an extra slash in the code blocks. I believe that this issue will take a little more time.
