### ISSUE TITLE
Link are not accesible shown  AccessDenied Error

### ISSUE THREAD

**Issue by BhavaniGaneshBalagam** [wavemaker/docs#67]
The following links are not accessible AccessDenied error

- [x] https://www.wavemaker.com/learn/app-development/widgets/chart/onbeforerender/

- [x] https://www.wavemaker.com/learn/how-tos/intercept-requests-responses-api-calls-one-place/

**Comment by prasanth-reddy-wavemaker-com** [comment]
this file /learn/intercept-requests-responses-api-calls-one-place.md needs to be moved into how-tos folder

**Comment by prasanth-reddy-wavemaker-com** [comment]
@BhavaniGaneshBalagam any progress on fixing /learn/intercept-requests-responses-api-calls-one-place.md? It is extremely simple to do it. I can show you how.
