### ISSUE TITLE
externalise the WM version number

### ISSUE THREAD

**Issue by wmrnaresh** [wavemaker/docs#72]
Move the hardcoded WM build number out of the repo and read it from the environment.

**Comment by wmrnaresh** [comment]
How to access the variables in .md files. https://github.com/facebook/docusaurus/issues/395

Might have to write a plugin to integrate the WM build number into the markdown file.

**Comment by prasanth-reddy-wavemaker-com** [comment]
This is good. Then new version deployments don't need code changes.

**Comment by rnaresh** [comment]
@sharath0033 started working on this

**Comment by rnaresh** [comment]
Added support for WM version umber
