### ISSUE TITLE
In mobile Manual build DOC, change the cordova version from 8.0.0 to 8.1.1( i.e chnage it to "Ensure that Cordova@8.1.1 is setup on your machine")

### ISSUE THREAD

**Issue by sandhya02** [wavemaker/docs#73]
Documentation link: https://www.wavemaker.com/learn/hybrid-mobile/mobile-build-manual/

Change Point 1. Ensure that Cordova@8.0.0 is setup on your machine.
to
Point 1. Ensure that Cordova@8.1.1 is setup on your machine.

**Comment by rnaresh** [comment]
https://www.wavemaker.com/learn/hybrid-mobile/mobile-build-manual/ the changes are already inplace.
