### ISSUE TITLE
[Issue] Datatable using row expansion become messy when changing page

### ISSUE THREAD

**Issue by derieff** [wavemaker/docs#740]
[Enter feedback here]

---
#### Document Details
* Document URL: https://github.com/wavemaker/docs/tree/master/learn/app-development/widgets/datalive/datatable/row-expansion-data-table.md
* Document PATH: /learn/app-development/widgets/datalive/datatable/row-expansion-data-table.md

**Comment by prasanth-reddy-wavemaker-com** [comment]
Thanks for taking time to report the problem you are having. I am assuming this to be something you are running into when using WaveMaker to develop an application. I have forwarded your request to our product support and they will get back to you. This github repo only contains the code needed to deploy our documentation and is not the right place to report issues you are facing inside the product. Like i said, i have already forwarded your query and will be closing this ticket here.
