### ISSUE TITLE
The link to the widget page style document is not opening.

### ISSUE THREAD

**Issue by prahaladmadepally** [wavemaker/docs#886]
[Enter feedback here]
There is a link to style document across each widget in [Widgets page](https://docs.wavemaker.com/learn/features/widgets.html). Please update the above link.

---
#### Document Details
* Document URL: https://github.com/wavemaker/docs/tree/master/learn/react-native/styles.md
* Document PATH: /learn/react-native/styles.md

**Comment by swethakundaram-wm** [comment]
Hi @prahaladmadepally, thanks for the feedback. The issue has been fixed.
